<?php

return [
    'defaults' => [
        'site_name' => 'My CMS',
        'favicon_media_id' => null,
        'date_format' => 'd.m.Y',
        'time_format' => 'H:i',
        'home_page_id' => null,
        'site_theme' => 'default',
        'site_featured_media_variant' => 'original',
        'media_default_insert_variant' => 'original',
        'media_upload_max_kb' => 20480,
        'media_image_optimize' => true,
        'media_image_max_width' => 1920,
        'media_image_max_height' => 1920,
        'media_image_jpg_quality' => 82,
        'media_image_webp_quality' => 80,
        'media_image_convert_to_webp' => true,
        'media_image_keep_original' => true,
        'media_image_create_thumbnails' => true,
        'admin_theme_mode' => 'dark',
        'admin_light_palette' => 'slate',
        'admin_dark_palette' => 'midnight',
        'cms_palette' => 'slate',
        'theme_assets_minify_css' => true,
        'theme_assets_minify_js' => true,
        'theme_assets_obfuscate_js' => false,
        'theme_assets_obfuscation_preset' => 'balanced',
        'theme_assets_combine_css' => true,
        'theme_assets_combine_js' => true,
        'theme_assets_separate_css' => false,
        'theme_assets_separate_js' => false,
        'theme_assets_defer_scripts' => true,
        'theme_assets_use_hash' => true,
        'cache_enabled' => true,
        'cache_data_enabled' => true,
        'cache_response_enabled' => true,
        'cache_response_ttl' => 0,
        'security_rate_limit_enabled' => true,
        'security_rate_limit_per_minute' => 180,
        'security_rate_limit_burst_per_10s' => 45,
        'security_ip_ban_seconds' => 900,
        'security_login_max_attempts' => 5,
        'security_login_decay_seconds' => 120,
        'security_login_ban_seconds' => 1800,
        'security_emergency_mode' => false,
        'security_emergency_message' => 'Сайт временно переведен в аварийный режим обслуживания. Попробуйте позже.',
    ],
];